### ISSUE TITLE
start-stop Script ( rc_domino_script ) overwrites custom DOMINO_SYSTEMD_NAME, DOMINO_PID_FILE and DOMINO_RC_NAME

### ISSUE THREAD

**Issue by patrickschneider** [IBM/domino-docker#21]
If DOMINO_SYSTEMD_NAME or DOMINO_PID_FILE or DOMINO_RC_NAME is customized in sysconfig/rc_domino_config_* , it will be overwritten by the values in rc_domino_script, lines 401 to 407
https://github.com/IBM/domino-docker/blob/master/start_script/rc_domino_script#L401
https://github.com/IBM/domino-docker/blob/master/start_script/rc_domino_script#L404
https://github.com/IBM/domino-docker/blob/master/start_script/rc_domino_script#L407

**Comment by Daniel-Nashed** [comment]
Thanks for the feedback! 
I removed the last assignment of DOMINO_PID_FILE. There have been some changes and I missed this one.

Also I changed the logic for DOMINO_SYSTEMD_NAME and DOMINO_RC_NAME.
They are now only set when they are still empty.

Both are just used for installation purposes in normal environments, not for Docker.
So they are not relevant for the project. 

Same is true for the DOMINO_PID_FILE setting. It should not be changed on Docker and the default will work.

How did you ran into it? Did yo use the scripts outside the Docker project?
Why did you want to change those settings? The customization is mainly intended for partitioned servers native on Linux.

The idea is to have a standardized environment. That's why we are recommending to keep the configuration as simple as possible.

In any case thanks for the feedback! and I submitted the fix to the develop branch..

Daniel

**Comment by patrickschneider** [comment]
Hi Daniel,

I used to scripts on a "standard" CentOS Domino with 2 Domino partitions. The changes are not relevant for the Docker environment, but I was downloading the scripts following your blog-post for the non-Docker-start/stop-Scripts from this location ( 
http://blog.nashcom.de/nashcomblog.nsf/dx/domino-on-linuxunix-start-script-new-install-location-optnashcomstartscript.htm ). So I thought that allthough it does not matter for the Docker environment, it could lead to problems if you want to use it on a "standard" Domino environment.
