### ISSUE TITLE
Run container with exist IDs

### ISSUE THREAD

**Issue by Rombs** [IBM/domino-docker#31]
Hi all!
Thx, it is great job !

I have some problem - could not set info to domino installer where it can get  files:
* cert.id
* server.id 
* admin.id

**My environment**
* MacOS Hight Sierra
* Docker:  2.2.0.5 (stable)

**Run command**
```bash
docker run -it -e "ServerName=docker" \  
    -e "ServerIDFile=/ids/docker.id" \  
    -e "OrganizationName=fbyte" \  
    -e "OrganizationIDFile=/ids/cert.id" \  
    -e "OrganizationPassword=12345" \
    -e "AdminFirstName=" \
    -e "AdminLastName=Salpagarov" \
    -e "AdminIDFile=/ids/admin.id" \
    -e "AdminPassword=12345" \
    -e "DominoDomainName=FBYTE" \
    -p 80:80 \
    -p 1352:1352 \
    -v /Users/Rombs/Dropbox/Work/FByte/ids:/ids \
    --stop-timeout=60 \
    --name docker \
    ibmcom/domino:10.0.1FP3
```
But when I try to connect to server from client with session of admin - I can't to do it.

```
---------------------------
You cannot authenticate server: docker/fbyte
---------------------------
The subject's public key found in the certificate is not the one stored in our ID file for that entity.    Check the local log file for details.

Do you want to access the server anyway?
---------------------------
Yes  No
---------------------------

---------------------------
IBM Notes
---------------------------
Server Error: The subject's public key found in the certificate is not the one stored in the server's ID file for that entity.  Check the server's log file for details.
---------------------------
ОК   
---------------------------

```

P. S.
I'm especially not mount volume to /local/notesdata - it's demo and I don't need save data

**Comment by Daniel-Nashed** [comment]
Hmmmm... From what I see, you are using the wrong value in the variable.
Unless you are having another sub directory called "ids" in /Users/Rombs/Dropbox/Work/FByte/ids the content of that directory is mounted into /. So the right path should be -e "AdminIDFile=/admin.id".

by the way: you cannot create directory when mounting a volume. that's why the image contains mount points of each directory you might need like /local/notesdata, /local/translog etc ..
Those are recreated when a mount is used for /local. 

In your case you don't have a persistent data directory in a volume on purpose an everything is written into the container and gone when you stop it, which is perfectly OK depending on what you want to do.

For all the variables specifying ID files and passwords we have an an explicit feature to copy ID files and get passwords from http locations or files -- this is intended for docker secrets support and other ways to specify passwords. So this should work with the right location specified.

So you could put the password into a file on this mounted volume - or write it temporary into another volume, instead of passing the password in the environment of the container. 

Let us know if the change of the variable works. Else I have to test on my own..

**Comment by mpradny** [comment]
Hi Rombs, 
were you able to solve your problem? I've tried to do something similar with V12 Early access and I'm getting the same error.  Sever console shows `[000126:000126-00007FAFA756A700] 09/22/2020 08:41:50   Error processing certificate created by /MPRBeta for /MPRBeta: The subject's public key found in the certificate is not the one stored in our ID file for that entity.` I've compared the certificates in names.nsf and it looks all good.
