### ISSUE TITLE
Start Domino Sametime Community Server

### ISSUE THREAD

**Issue by agorosti** [IBM/domino-docker#35]
Hi,

I recently installaed a Sametime Community server on top of Domino 11.

Until now, I was starting the servers with the rc.domino script,  but they do not longer works when Sametime is installed.  It seems that now,  the provided ststart.sh should be run in order de related Sametime Services also start with Domino.  However, that script is much more limited, you have not access to the console,  there is not automatic startup at reboot (does not work as a service), etc.

Can be rd.domino scprits addapted to support also Sametime ?

Thks!

**Comment by Daniel-Nashed** [comment]
Sorry for the delay replying. The Nash!Com Start Script is included in this project. But the start script in general is still maintained by me separately.
The start script was never supported on ST, because there have been technical issues on SLES. 
It turned out those have been SUSE rc related and when switching to systemd and removing the "rc" includes from SLES, ST works fine.
So I added basic support for ST in the start script by for Sametime 11 after adding the additional ST lib path needed.
Last week I added the log cleanup from the ststart script, so you have a fully integrated solution.

The always latest version of the start script is right now in the start_script directory in the develop branch of this project.
