### ISSUE TITLE
Install borgbackup is broken on centos:8

### ISSUE THREAD

**Issue by smejkal** [IBM/domino-docker#41]
I added a section to script_lib.sh to enable Powertools

```
install_powertools()
{
  if [ -x /usr/bin/dnf ]; then

    dnf -y install epel-release

    dnf -y config-manager --set-enabled epel

    dnf -y config-manager --set-enabled powertools

  fi
}
```

-----------------------

And execute this function in install_domino.sh

```
if [ "$BORG_INSTALL" = "yes" ]; then

    if [ -e /etc/centos-release ]; then
      header "Installing Borg Backup"
      install_powertools
      install_package epel-release
      install_package borgbackup openssh-clients
    fi
fi
```
Only my workaround to enable borg on image. I know this would not work in all constellations.

**Comment by Daniel-Nashed** [comment]
We can't just add powertools to our image! We need to keep the image small. 
BorgBackup is an add-on which is not really a core component of the Docker image.

BorgBackup is broken in the CentOS distribution and we can't really fix it.
I looked at it and there would be an alternate way to install BorgBackup directly from GitHub.

Here is the test I did with BorgBackup install. But I don't know if I want to download software from GitHub instead of having it installed from a secure repository.

```
curl -L https://github.com/borgbackup/borg/releases/download/1.1.17/borg-linux64 -o /usr/bin/borg; chmod 555 /usr/bin/borg; borg -V
```

Also BorgBackup has no latest version link. We would need to maintain that link manually. 
But this would be a work-around for now. 

Are you using BorgBackup on Docker with the Domino integration?

Do you have any other feedback about it? I didn't hear much yet.

What do you think about installing from GitHub during image build?
Can we assume that the image build process can download? 
If not curl commands can automatically leverage a defined proxy to download. That should work fine.

**Comment by smejkal** [comment]
Yes, thats an important approach to hold the image size small. But you activate the EPEL repository anyway when the -borg option is set, only the powertools are not enabled.

I compared the image size with following configurations:

```
RUN dnf -y update && \
    dnf -y install openssl bc which nano unzip lsof gdb file net-tools hostname cpio procps-ng diffutils glibc-langpack-en glibc-langpack-de && \
    dnf -y install epel-release && \
    rm -rf $LocalInstallDir
```
and

```
RUN dnf -y update && \
    dnf -y install openssl bc which nano unzip lsof gdb file net-tools hostname cpio procps-ng diffutils glibc-langpack-en glibc-langpack-de && \
    dnf -y install epel-release && dnf -y config-manager --set-enabled epel && dnf -y config-manager --set-enabled powertools && \
    rm -rf $LocalInstallDir
```

Result is 489941605 to 489943729, round about 2k

It's no problem to me to install borg from github. But, you provide the -borg option and cause it's not working, I tried this workaround.

Yes, I evaluate the borg and domino integration since yesterday ;-) 

Important is to set the BORG_PASSPHRASE with domino_container env if the borg repository is encrypted.

After this it works fine for one day...

**Comment by Daniel-Nashed** [comment]
Oh now I see "powertools" has the missing dependencies.

But your commands did not work for me.

I used this in a container:

```
yum install dnf-plugins-core
yum config-manager --set-enabled powertools
```

BorgBackup is a special build option. So I am not that critical making a change like this.

I think for now this might be a good idea to add those two commands.
Working with CentOS for years, I never had to look into powertools.

We have to find out anyway what we do soon. CentOS 8 is running out of support.
There are many other build environments we support.
But we have to pick one to be the default.

If it would be UBI, BorgBackup will be more difficult to add.
I am looking into that right now.. 

It's not the size of an image but we really have to make sure we are getting packages from the right sources too.

I looking into Rocky Linux right now which works the same way.

**Comment by smejkal** [comment]
I can understand your objections very well and I agree with them.

Yes, CentOS is being phased out and Stream is not yet officially supported. I also think it's a good idea to use the same base as the HCL images with UBI.

Before Borg I used rdiff-backup with duplicity as a backup solution. But there are the same problems that they are not in the standard repository.

What is a good alternative that works with Domino Backup?

**Comment by Daniel-Nashed** [comment]
CentOS Stream is supported by Domino in the same way other Linux distributions are supported when they meet the requirements.

See a [link on my blog](https://blog.nashcom.de/nashcomblog.nsf/dx/production-migrated-to-centos-8-stream.htm) for details. 
We really want to stay with something close to CentOS.  
UBI has some limitations we don't like. For example there only English glibc support unless you are a RHEL customer with full repositories.

And some tools like BorgBackup are not part of it. We are currently waiting for what is happening. If there will be a Docker image for CentOS stream which would be our preference. 

We have many other distributions tested and supported with separate dockerfiles in this repository. So it would be a simple switch to any other primary platform. 

For the backup it really depends what you are looking for in which type of environment.
BorgBackup is a good choice for a smaller environment. But for large servers having a enterprise level backup would make a lot of sense.

On the other side Domino backup supports different storage back-ends for backup. So you could store data also on a ZFS compressed and de-duplicated storage and then have secondary backup solution to ensure this storage is protected.

HCL is working on Veeam integration, which is one of the most commonly used backup applications.
But this is also more an enterprise level backup for VM environments running on VSphere (no ESXi only because of missing storage APIs) and Hyper-V.

Domino Backup is designed to run on many different environments, but the focus for V12.0.0 was to get the functionality implemented to build a base. And we are in the phase where customers/partners and HCL are implementing integrations.

There will be a new HCL GitHub repository for Domino Backup soon. If you are interested in a preview let me know and I will add you.

**Comment by Daniel-Nashed** [comment]
Looking into it again while switching the default image from CentOS 8 to CentOS 8 Stream.  
They still did not fix the dependencies and your suggestion adding the powertools repo is the best way to go.  
So only when selecting -borg I am adding the powertools repo.  
As you said it is not adding more software.  

So there will be an update later today, when testing goes well. Looks good so far...

**Comment by smejkal** [comment]
Thanks Daniel! Works great with the 12.0.1 build.

**Comment by Daniel-Nashed** [comment]
I have added another way to install directly from the binary package. check out the latest version.

**Comment by smejkal** [comment]
Hi Daniel, 

after moving the start scripts to your Github account, the borg script files can no longer be copied when building with the -borg option, because they are no longer in the start_script directory.

I've now copied them to /opt/hcl/domino/backup/borg with docker cp.

What is your recommendation to fix this?

**Comment by Daniel-Nashed** [comment]
I updated the development tree already. but it is not yet in the main tree.  It should work with the existing start script.
can you try it out with the develop tree? As I mentioned I updated borg support and reworked the installation.

**Comment by Daniel-Nashed** [comment]
@smejkal did you got it working? Does the new method work for you?

Thanks
Daniel

**Comment by Daniel-Nashed** [comment]
I did not hear anything back and we have replaced the Borg backup installation completely.   
Borg Backup is now downloaded from the Borg GitHub repository by default.  
And it is listed in the software.txt with reference to the latest versions.
