### ISSUE TITLE
Problems with v10.0.1

### ISSUE THREAD

**Issue by B-z-F** [IBM/domino-docker#48]
Hi,
in software.txt is missing line for Domino_10.0.1FP5_Linux64.tar.

But build fails even with FP4 (files copied to dir software) - command:
`./build.sh domino 10.0.1 FP4`

results in
```
...
Successfully downloaded, extracted & checked: [http://172.17.0.2/DOM_SVR_V10.0.1_64_BIT_Lnx.tar]
...
Successfully downloaded, extracted & checked: [http://172.17.0.2/Domino_10.0.1FP4_Linux64.tar]

--------------------
Installing domino 10.0.1
--------------------

Running Domino Silent Install -- This takes a while ...

/tmp/install/install_domino.sh: line 90: ./install: No such file or directory
find: '/opt/hcl/domino': No such file or directory
mv: cannot stat '': No such file or directory

--------------------
cat: /tmp/domino-container/install_domino.log: No such file or directory
--------------------

ERROR - Domino Installation failed!!!
The command '/bin/sh -c $LocalInstallDir/install_domino.sh &&   rm -rf $LocalInstallDir' returned a non-zero code: 1
Image build failed!
```

Tested on Rocky Linux release 8.6 with Docker Engine - Community Version: 20.10.16

**Comment by Daniel-Nashed** [comment]
Just tested with 10.0.1 and I am also getting an error (downloaded this old version just for you, by the way).
There is only limited support for older versions. Automated configuration has been removed for versions before 12.0, because this the version introducing one-touch setup.

A current 11.0.1 FP still works to install and we currently cannot justify the effort looking into the build error for 10.0.1 
Containers are a modern deployment option, which should be used with current Domino versions.
If you really need an older version, you might want to look into it on your own. The scripts are all open.

**Comment by Daniel-Nashed** [comment]
OK I found where the problem is. 
The tar files for 10.0.1 contains another sub-directory.
The older scripts had a special case for Domino 10.0.1 and set those directories.
I would tend to remove support for Domino 10.0.1 unless there is really a good reason to keep it.
You can use an earlier script and add the FP version on your own.

**Comment by Daniel-Nashed** [comment]
Now looking again into the changes, I see what the issue is.
Domino 10.0.x was still installed into `/opt/ibm/domino` and the installer had another sub-directory.  
When refactoring the project, we removed version 9.0.1 already. And we should have removed 10.0.x too, because it is build in the same way. 

There have been special checks to detect the version to install and there was separate logic for the installer.

See details here --> https://github.com/HCL-TECH-SOFTWARE/domino-container/blob/e93cadfa837c7cd581c3b50ba6f7b2dbda16ba6b/dockerfiles/domino/install_dir/install_domino.sh#L128

I really think it makes time to move to a new release, when using Docker.
You can still use the older scripts if you want to and add the fixpack you are looking for.

But given that it does not work for a while and nobody asked about it, I think dropping version 10.0.x support is the right step for the community image. I really should have removed the version from `software.txt` already.

I still would like to know, why you need 10.0.x as a container. Feel free to contact me off-line, if you don't want to post here.

-- Daniel

**Comment by Daniel-Nashed** [comment]
10.0.x support has been removed and I cleaned up software.txt, which was a left over.
The older versions of the script would still support 10.0.x.
We really want admins to switch to Domino 12.0.1 to have the full OneTouch functionality to setup servers on Docker -- among other new features.
