### ISSUE TITLE
Install borg is broken (again)

### ISSUE THREAD

**Issue by smejkal** [IBM/domino-docker#54]
```
--------------------------------------------------------------------------------
Installing Domino Borg Backup integration
--------------------------------------------------------------------------------

/tmp/install/install_domino.sh: line 718: /tmp/install/domino-startscript/install_borg: No such file or directory

```

install_borg was part of the start-script. Cause this part has moved, the install_borg is missing.

As workaround I copied install_borg from start-script to $INSTALL_DIR/domino-startscript

**Comment by Daniel-Nashed** [comment]
Thanks for the hint! 

I had to rework the start script integration, because the repository is now also used for the HCL official image.
So I just included the needed components into the project.

I missed the Borg installer.

**Comment by Daniel-Nashed** [comment]
just added the file again. but it looks like more is missing! the whole borg directory isn't included. 
those files are needed for the integration!

can you explain, why it is working for you by just copying the install_borg file? 

from what I see we need to add the files again to make them available directly from the docker-container project.

I am fixing it right now in way, that you could even deploy a newer version of it with a newer start script, which has it's own download packaging optionally. 

the first build is done and I am testing.. I will push an update to the develop branch later today.

**Comment by smejkal** [comment]
No, it's not working, i thought it.

Borg is installed, but the backup scripts (from extra/backup/borg) are missing. 

Edit:

> the first build is done and I am testing.. I will push an update to the develop branch later today.

Great, thanks!

**Comment by Daniel-Nashed** [comment]
updated the development branch with a fix. all files are back. and I moved the place where it is hooked in to work with the external start script installer plug-in (don't worry about this part. this is more for special cases).

all the files are back!  next time please do an end to end test, before proposing a solution for an issue ;-)

let me know if this works!

**Comment by smejkal** [comment]
I'm really sorry. You just work too fast, I was still testing and researching what causes the problem, you already answered ;-)

It works with the develop branch.

Thank you so much!

**Comment by smejkal** [comment]
Hi Daniel,

Unfortunately I have to reopen the issue.

In the develop branch, the build works for domino, but throws following error when I build traveler:

```
--------------------------------------------------------------------------------
Running Traveler silent install
--------------------------------------------------------------------------------

cp: cannot stat '/local/notesdata/IBM_TECHNICAL_SUPPORT/traveler/logs/TravelerInstall.log': No such file or directory
```

And this regardless of whether the -borg option was used or not.

```
./build.sh domino 12.0.1 FP1
./build.sh -from=hclcom/domino:12.0.1FP1 traveler 12.0.1FP2
```

In the main branch, the traveler build works. But, as is known, not with the -borg option.

**Comment by Daniel-Nashed** [comment]
Ooops! 

But this has nothing to do with the Borg option. Can you create a separate issue for each problem in future to keep track, please. 

There was a change in the way the notes.ini is packed into the install data tar file.
The **notes.ini** is now renamed to `notes.ini.instal` before creating the tar to ensure we can unpack the tar completely in one go on updates without the risk overwriting a productive notes.ini.

Stay tuned. I am working on a fix...

**Comment by Daniel-Nashed** [comment]
Should be fixed. Updated the development branch. And tested with Traveler 12.0.1 + 12.0.2 EAP.
Let me know if it works for you as well.

I also improved the Traveler installer error logging and the log copy command.
Now the Traveler error log is also dumped, when an error occurs. this makes troubleshooting a bit easier in future.

**Comment by smejkal** [comment]
Thanks, the build issue is also fixed.

**Comment by smejkal** [comment]
Hi Daniel,

I guess Borg is not your friend ;-)

After switching to CentOS Stream 9 and glibc 2.34, borg is not working again.

Even if I call `borg info .` inside the container, the following error message appears:

`[9710] Error loading Python lib '/tmp/_MEINyen0F/libpython3.9.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory`

Same error message at the command: `borg --version`

The latest Borg release is 1.2.4 (apart from the 2.x beta) and the release download contains a borg-linuxnew64 (built on Debian 11 "Bullseye" with glibc 2.31). This version may work in conjunction with CentOS Stream 9

software.txt contains:
`borg|1.2.0|https://github.com/borgbackup/borg/releases/download/1.2.0/borg-linux64|-|df271a523434a445c783c1a0bc3dd599521d6a6a25acd2766e9a5577edb6018f
`

How can I create the hash to try it out?

**Comment by Daniel-Nashed** [comment]
This is a moving target. I took a quick look. What is broken is the OpenSSL dependency.

Right now default borg is installed from the GitHub repository by just copying the binary. The binary does not work for CentOS Stream 9. Also the latest binary does not work when you just copy it.
I checked the CentOS Stream 9 repository and they now ship a current version.
So setting the default back to use what is in the Linux distribution would make sense.

I just modified the **software/current_version.txt** locally and tested.
If you don't specify a version, it will set the version to the version from **current_version.txt**.

Without an entry in this file, the installer uses the borg version in the distribution.
This seems to be the best choice today and this will be the new standard.

The other option you have is to use `-borg=yes` instead of just `-borg`. this will also override the default version in **current_version.txt**.

I have changed the default and pushed the change to the develop branch right now.

Please let me know if this works for you.

Daniel

**Comment by Daniel-Nashed** [comment]
the hashes are sha256 hashes. this is the same for all software packages. 
I added this new option at some point to be independent from what is in the distributions.
turns out with OpenSSL dependencies and running and building on different distributions, this isn't a good idea any more.

Also troubleshooting it, isn't a good idea. We should use what borg includes into the distributions. the version is up to date.

By the way CentOS Stream 9 is at:

```
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

The error message isn't even a direct Borg error message. It's a Python dependency.

**Comment by smejkal** [comment]
> Without an entry in this file, the installer uses the borg version in the distribution.
> This seems to be the best choice today and this will be the new standard.

This is really a great implementation.

It works without the entry in the current_version.txt

Thanks!
