### ISSUE TITLE
Show console.log in docker logs

### ISSUE THREAD

**Issue by edy** [IBM/domino-docker#57]
A few years ago, I created a Docker image for Domino myself.

In the past it always helped me a lot to output the console via "docker logs".

I have included the following line:

```bash
	# pipe notes.log into docker logs
	# $$ is the PID of the current shell.
	# tail terminates after PID dies
	tail --pid $$ -F -n0 /local/notesdata/notes.log &
```

Today I would use `/local/notesdata/IBM_TECHNICAL_SUPPORT/console.log`.

What do you think about this idea?

**Comment by Daniel-Nashed** [comment]
it's already possible. but you will loose the option to use the live console.
It's arguable if all the logs from a Domino server should be forwarded to the container environment.
usually Domino admins and K8s admins are not the same people. 
K8s care more about general error messages. Domino admins care about the details.

For Docker environments the Domino admin might be the same person also maintaining the Docker environment.
I would still prepare to use the Domino start script live console and not forward all the data to the container standard output.

It's a project decision to not forward the logs. of course you could also mirror the console. But why do you want the additional overhead.

I could look into adding the mirroring as an option. But you are the first one to ask about it. 
So I am not sure how many admins would use it.

why do you want to see all the logs via Docker? what would be the use case for seeing the complete Domino log?

**Comment by edy** [comment]
Die Macht der Gewohnheit :-)

I have a Docker-only environment and in the past it was pretty easy for me to quickly check for an error message or anything else without having to launch the HCL apps (e.g. Administrator). In case of emergency even possible on the road without much hassle on the smartphone.

This does not happen often, just makes my job easier.

With the One Touch Setup, it would have made troubleshooting easier for me. I had to search for the log in the docker volume when errors occurred during setup.

**Comment by Daniel-Nashed** [comment]
there is a ```domino log``` and ```domino console``` command inside the container.
And the **dominoctl** makes running commands inside the container very simple.

You can also use a simple ```docker exec -it container-name domino console```.

There are not many admins using the Docker logs to log all the results, because of this integration.
Not sure what your background is. But most admins are coming from the Domino on Linux native world and not form the Docker world. And most admins would look into the Domino logs directly and not leverage Docker log functionality.

Forwarding the logs and using the live console from **Domino start script** is a bit problematic. That's why I would like to avoid it.
