### ISSUE TITLE
Building on Mac M1 seems to never end...

### ISSUE THREAD

**Issue by john-dalsgaard** [IBM/domino-docker#58]
Trying to build a docker image for my QNAP NAS. I have cloned the repo, downloaded (or rather moved) the server "tar" file into the software subdir - and then run "./build.sh domino"....

And that seems to take forever...

![image](https://user-images.githubusercontent.com/2842073/226555883-7dd4b585-8e63-4d3d-9820-ca8cf831d05d.png)

**Comment by Daniel-Nashed** [comment]
Building on Apple Silicon is a challenge. This is due to the architecture differences and the emulation.
Docker out of the box shows the same behavior on my Mac Mini M2.

I got to a decent build time around 14 minutes by using the following settings:

- Use the latest version
- Rosetta x64/amd64 emulation on Apple Silicon in the experimental settings.
- Enable VirtioFS for better file-system performance.

Note: the first setting is what will make the main difference. But is experimental today.

ARM is not an officially supported build or run-time platform for Domino on Linux.
It might work and is good for a local environment. But not intended for production.

I have also tested Rancher Desktop this morning, which has almost double the build time.

Generally it would make sense to build on a virtual machine on Intel architecture. 
It looks like specially the Install Anywhere cross platform Java installer is running slow.

This is a platform issue, which hopefully gets better in every Docker and Rancher Desktop release.
We will write up a document for Apple Silicon to not let others run into similar issues.

Please test the settings and let us know if this helps on your M1 and what your performance is.

**Comment by john-dalsgaard** [comment]
I had to download the newest Docker Desktop (now on 4.17.0) and then I had the option under "Fetaures in development" to enable "Rosetta for x86/amd86 emulation...".

Rerunning the build command succeeded:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2842073/226585511-4b3572eb-64e6-410d-b032-a98cf3742a7c.png">

in 15:35 minutes.

Also enabled VirtioFS as sharing file system under "General".

**Comment by thampel** [comment]
Nice - can we close this issue now?

**Comment by john-dalsgaard** [comment]
Yep, I should think so! Thanks!

**Comment by Daniel-Nashed** [comment]
Sadly building and running Domino Intel code on ARM is a moving target. 
It isn't reliable and can't be supported today.

We cannot recommend trying to build or run the Domino container image on Apple Silicon or other ARM based platforms today. It's running an emulation which has limitations even using Docker with Rosetta support.

You can be sure the team likes the ARM and specially Apple Silicon.
But this combination isn't reliable for the container image today.

-- Daniel
