### ISSUE TITLE
Add Docker for Windows Support

### ISSUE THREAD

**Issue by ghost** [IBM/domino-docker#7]
Currently Docker for Windows is not supported. As Notes developers we are generally already running on Windows machines, so this makes a lot of sense.

**Comment by paulswithers** [comment]
I can run the bash script build.sh using Cmdr and starting a bash console. This may be an option because I have installed git command line interface, which installs git-bash. But it failed with the error in the screenshot below. 

![image](https://user-images.githubusercontent.com/3721367/56965959-24301080-6b56-11e9-9b1f-f311a83934bc.png)

Looking at this [StackOverflow question](https://stackoverflow.com/questions/50608301/docker-mounted-volume-adds-c-to-end-of-windows-path-when-translating-from-linux), that may also be because of git-bash. Updating build.sh to uncomment line 36 and setting it to `SOFTWARE_DIR=/${PWD}/software` got it to work.

![image](https://user-images.githubusercontent.com/3721367/56970023-3150fd80-6b5e-11e9-93b4-11b90daadd97.png)

However, I'm now getting an error with either the command to run install_domino.sh or something in the file itself. It looks like somewhere there's a carriage return using DOS line endings, which is failing when the file is copied into the Docker container.

![image](https://user-images.githubusercontent.com/3721367/56970102-5ba2bb00-6b5e-11e9-9d7b-4953c9db6970.png)

**Comment by ghost** [comment]
Hi @paulswithers. The scripts are supposed to be run with PowerShell on Windows. Open Powershell prompt on windows and run the build.ps1 script

**Comment by ghost** [comment]
@paulswithers oops, I already made a pull request for this. #8 but it is still pending.

**Comment by paulswithers** [comment]
That explains why I couldn't see the file in the repo ;-)

I've subsequently followed the instructions in this [StackOverflow question](https://stackoverflow.com/questions/49228693/how-to-change-eol-for-all-files-from-clrf-to-lf-in-visual-studio-code) in a git terminal to force CRLF to LF. (I reinstalled my PC recently, and my global git config settings may be out-of-date.) That, combined with setting the SOFTWARE_DIR, allows the build to run successfully from bash for Windows.

**Comment by Daniel-Nashed** [comment]
Oh this old issue is still open. We still have no support for Windows and we still have no plans to add build support for Windows.
Today most admins have also WSL2 if running Windows. You can use Windows as a run-time environment. But you need at least WSL2 to build it. Docker has evolved and now uses WSL2 only. 

We have official build support for WSL2 and it works with Ubuntu and also SUSE Leap. It should also work with other distributions. But I only personally tested with those two.

Thanks
Daniel
