### ISSUE TITLE
Unable to build with the latest (1.1.5) LEAP version

### ISSUE THREAD

**Issue by finasoft** [IBM/domino-docker#71]
The current (27/8/2024) version of the script does not support Domino LEAP 1.1.5.

I downloaded the latest 1.1.5 Domino LEAP version do the /local/software directory. The file itself was hcl.dleap-1.1.5.4.zip. I modified the current_version.txt to have "leap|1.1.5" and I added the following line to the software.txt 

leap|1.1.5|hcl.dleap-1.1.5.4.zip|-|61dce3bb8ba71383a506e4f7a3673e4fdd55db12ec204246e4c7c3fc1cf5806e

The "61dc...." part was copied from the HCL software download portal. I was not able to find what to place instead of "-".
./build.sh -checkonly and ./build.sh -verifyonly run successfully with this configuration. Yet the build failed with the process complaining that it could not download the [leap] [1.1.5].

Going back to Domino Leap 1.1.4 resulted in successful build.

**Comment by Daniel-Nashed** [comment]
I have just updated Leap to the latest version in the develop and main branch.

**Comment by finasoft** [comment]
Just to understand - where do you get the first hash from? The one just after the file name.

**Comment by Daniel-Nashed** [comment]
If you refer the to the the entry behind the **SHA256** hash, that's the **fileID** not a hash.
There should be no need to add entries on your own. 

The **fileID** is the download file ID from MyHCLSoftware portal.
I just added it last month for simplifying the automated download. Before the automated download needed to search for the **fileID** because this is the only software package download lookup key.

**Comment by finasoft** [comment]
Thank you.

**Comment by finasoft** [comment]
Both builds (v14fp2 and v12.0.2fp4) completed successfuly.
